In [9]:
# package
import pandas as pd
import re
from datetime import datetime


import requests
from bs4 import BeautifulSoup as bs
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from urllib.parse import urlencode, quote_plus, urlparse
from urllib.request import urlopen
import urllib

from bs4 import BeautifulSoup
import json

from datetime import date, timedelta
from time import sleep
import schedule

#import pyautogui as  pag
import time
from datetime import datetime

In [4]:
## 크롤링
# 서울특별시 강남구 개포동으로 연습
#연습1 파이썬 사이트 가서 python 검색


#연습1 파이썬 사이트 가서 python 검색
driver = webdriver.Chrome('C:/chromedriver')
driver.implicitly_wait(3) #암묵적으로 웹 자원 로드를 위해 3초까지 기다려 준다.
driver.get('https://onland.kbstar.com/quics?page=C059652')

action = ActionChains(driver)
search = driver.find_element_by_xpath('//*[@id="unifiedSearchKeyword"]')
action.move_to_element(search).click().send_keys('서울특별시 강남구 개포동').send_keys(Keys.RETURN).perform()

action = ActionChains(driver)
step_1 = driver.find_element_by_xpath('//*[@id="unifiedSearchResult"]/div[1]/ul/li/a/b[1]')
action.move_to_element(step_1).click().perform()

action = ActionChains(driver)
step_2 = driver.find_element_by_xpath('//*[@id="IBF"]/div/div[3]/div[1]')
action.move_to_element(step_2).click().perform()

action = ActionChains(driver)
step_3 = driver.find_element_by_xpath('//*[@id="IBF"]/div/div[3]/div[2]/div/div/div[1]/ul/li[2]/label/span[1]')
action.move_to_element(step_3).click().perform()


action = ActionChains(driver)
step_4 = driver.find_element_by_xpath('//*[@id="maemulTab"]/a[2]')
action.move_to_element(step_4).click().perform()

html = driver.page_source
soup = bs(html, 'lxml')
lis = soup.select('#mCSB_19_container > .map_mod_list')  # 개별 list쪽 크롤링 



today = datetime.today().strftime("%Y%m%d")
korean = re.compile('[\u3131-\u3163\uac00-\ud7a3]+')


apt, price, area, date = [], [], [], []
count = -1
for i in lis:
    count += 1
        
    apt.append(i.find('dt').text)
    price.append(i.find('dd',{'class':'sprice'}).text[2:])
    area.append(i.find('span',{'class':'ellips'}).find('span').text)
    date.append(i.find('dd',{'class':'mod_btn'}).text[6:14])

    if (int(today) - int('20' + date[count].replace('.',''))) > 13:
        break
    

estate = pd.DataFrame({'apt':apt, 'price':price, 'area':area, 'date':date})
estate['area'] = estate['area'].apply(lambda x : int(x[x.find('/') + 1 : -2]))

estate['size'] = estate['area'].apply(lambda x : '중소형' if x <= 59
                                      else '중대형' if x <=84
                                      else '초대형')

In [12]:
estate

                  apt     price  area      date size
0       래미안블레스티지 222동  18억5,000    59  20.02.17  중소형
1       래미안블레스티지 201동  17억8,000    59  20.02.17  중소형
2       주공고층7단지. 706동       20억    73  20.02.17  중대형
3       래미안블레스티지 215동       29억    99  20.02.17  초대형
4       래미안블레스티지 217동       19억    59  20.02.17  중소형
5       래미안블레스티지 213동       35억   126  20.02.17  초대형
6       래미안블레스티지 202동  19억6,000    59  20.02.17  중소형
7       래미안블레스티지 221동  25억9,000    84  20.02.17  중대형
8       래미안블레스티지 214동  37억5,000   126  20.02.17  초대형
9       래미안블레스티지 217동  19억5,000    59  20.02.17  중소형
10      래미안블레스티지 221동       26억    84  20.02.17  중대형
11      래미안블레스티지 213동       35억   126  20.02.17  초대형
12      주공고층7단지. 705동  22억7,000    83  20.02.17  중대형
13      주공고층5단지. 501동  21억8,000    83  20.02.17  중대형
14      주공고층6단지. 602동  21억8,000    83  20.02.17  중대형
15  개포1차지구(주공1단지) 47동  17억5,000    35  20.02.17  중소형
16      래미안블레스티지 202동       20억    59  20.02.17  중소형
17      래미안블레스티지 211동       27억    84  20.02.17  중대형
18      래미안블레스티지 204동  25억2,000    84  20.02.17  중대형
19      래미안블레스티지 213동       35억   126  20.02.17  초대형
20      래미안블레스티지 213동  34억5,000   113  20.02.17  초대형
21      래미안블레스티지 215동  29억5,000    99  20.02.17  초대형
22      래미안블레스티지 204동  25억2,000    84  20.02.17  중대형
23      래미안블레스티지 215동  29억4,000    99  20.02.17  초대형
24      래미안블레스티지 215동  29억5,000    99  20.02.17  초대형
25      래미안블레스티지 204동  25억3,000    84  20.02.17  중대형
26      주공고층5단지. 506동  18억5,000    61  20.02.17  중대형
27      래미안블레스티지 213동  24억8,000   126  20.02.17  초대형
28      래미안블레스티지 206동  18억7,000    59  20.02.17  중소형
29      래미안블레스티지 204동  25억3,000    84  20.02.17  중대형

In [10]:
# 지역코드 파일 다운받은 주소
# "https://www.mois.go.kr/frt/bbs/type001/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000052&nttId=61552"

# 지역 코드 데이터프레임
code = pd.read_excel("KIKcd_B.20180122.xlsx")
code = code[(code["시도명"]=="서울특별시")]    
code = code[code["읍면동명"].isnull()==True]
code = code[code["시군구명"].isnull() == False]
code["gu_code"] = code["법정동코드"].astype(str).str[0:5]
code = code[['시도명', '시군구명', 'gu_code']]
code.columns = ['si','gu','gu_code']
code = code.reset_index(drop = True)

# 실거래가 오픈 API 크롤링
# 크롤링 함수만들기
def get_data(ym, lawd_cd):
    
    API_key = 'L0KZ2ICoL5OWOUXZbOCKEePlYdIOM%2F5hh5a7G3Aasau1slDVmsKI9XOoQyFsVcQrkh6ipq0%2Fm38n3PaWC2asfQ%3D%3D'
    endpoint = 'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev'
    url = endpoint + "?serviceKey=" + API_key + "&pageNo=1" + "&numOfRows=5000" + \
            "&LAWD_CD=" + lawd_cd + "&DEAL_YMD=" + ym
    
    resultXML = urlopen(url)
    result = resultXML.read()
    xmlsoup = BeautifulSoup(result, 'lxml-xml')
    te = xmlsoup.find_all('item')

    df = pd.DataFrame()
    for t in te:
        dong = t.find('법정동').text
        apt = t.find('아파트').text
        year = t.find('년').text
        month = t.find('월').text
        day = t.find('일').text
        area = t.find('전용면적').text
        price = int(t.find('거래금액').text.replace(',',''))
        if int(month) < 10: month = '0' + month
        if int(day) < 10: day = '0' + day
        date = year + month + day
        if area <= '59': size = '중소형' # 여기 수정 필요 11! < 80 true로 인식. int()는 .때문에 오류
        elif area <= '84': size = '중대형' 
        else: size = '초대형'
            
        temp = pd.DataFrame(([[dong, apt, area, date, price, size]]),
                        columns=["dong","apt","area","date","price","size"])
        df = pd.concat([df,temp])
        
    df = df.reset_index(drop = True)
    
    return df


# 지난달, 이번달
today = date.today().strftime("%Y%m%d")[:6]
month_ago = (date.today().replace(day = 1) - timedelta(days = 1)).strftime('%Y%m%d')[:6]
time = [month_ago, today]

# 데이터 저장
df_trade = pd.DataFrame()
for t in time:
    for co in code['gu_code']:
        temp = get_data(t, co)
        df_trade = pd.concat([df_trade, temp])
df_trade = df_trade.reset_index(drop = True)
df_trade['size'] = df_trade['area'].apply(lambda x : '중소형' if int(x[0:x.find('.')]) <=59
                                          else '중대형' if int(x[0:x.find('.')]) <=84
                                          else '대형')
df_trade['pyeong'] = df_trade['area'].apply(lambda x : int(x[0:x.find('.')]) / 3.3)
df_trade['price_per_3.3'] = (df_trade['price'] / df_trade['pyeong']).round()

In [11]:
df_trade

,dong,apt,area,date,price,size,pyeong,price_per_3.3
0,필운동,신동아블루아광화문의 꿈,111.97,20200103,100000,대형,33.636364,2973.0
1,사직동,광화문풍림스페이스본(106동),163.33,20200102,162000,대형,49.393939,3280.0
2,내수동,세종로대우,109.91,20200106,88000,대형,33.030303,2664.0
3,내수동,킹스매너,194.43,20200109,130000,대형,58.787879,2211.0
4,내수동,경희궁 파크팰리스,148.09,20200120,149000,대형,44.848485,3322.0
5,인의동,효성쥬얼리시티,84.7,20200110,52000,중대형,25.454545,2043.0
6,인의동,효성쥬얼리시티,84.7,20200112,69000,중대형,25.454545,2711.0
7,효제동,포레스트힐시티,22.0584,20200110,25000,중소형,6.666667,3750.0
8,연건동,이화에수풀,16.98,20200118,21500,중소형,4.848485,4434.0
9,충신동,CS타워,21.94,20200118,17600,중소형,6.363636,2766.0
10,명륜3가,한빛,59.73,20200110,34500,중소형,17.878788,1930.0
11,창신동,창신쌍용2,79.87,20200103,51000,중대형,23.939394,2130.0
12,창신동,창신쌍용2,64.66,20200103,49500,중대형,19.393939,2552.0
13,창신동,두산,59.95,20200103,64000,중소형,17.878788,3580.0
14,창신동,창신쌍용1,79.87,20200104,64800,중대형,23.939394,2707.0
15,창신동,창신쌍용2,79.87,20200107,54500,중대형,23.939394,2277.0
16,창신동,창신쌍용1,54.7,20200109,49400,중소형,16.363636,3019.0
17,창신동,창신쌍용2,54.7,20200111,44400,중소형,16.363636,2713.0
18,창신동,동대문맨션,95.54,20200113,37000,대형,28.787879,1285.0
19,창신동,창신쌍용2,64.66,20200117,49000,중대형,19.393939,2527.0
20,창신동,창신쌍용2,79.87,20200117,56700,중대형,23.939394,2368.0
21,창신동,창신쌍용1,79.87,20200118,59000,중대형,23.939394,2465.0
22,창신동,창신쌍용2,79.87,20200118,57800,중대형,23.939394,2414.0
23,창신동,창신쌍용2,54.7,20200118,44500,중소형,16.363636,2719.0
24,창신동,창신쌍용1,79.87,20200120,68000,중대형,23.939394,2841.0
25,창신동,창신쌍용1,79.87,20200122,60000,중대형,23.939394,2506.0
26,창신동,창신쌍용2,64.66,20200129,46700,중대형,19.393939,2408.0
27,창신동,창신쌍용2,64.66,20200130,48500,중대형,19.393939,2501.0
28,숭인동,종로센트레빌,59.92,20200102,68000,중소형,17.878788,3803.0
29,숭인동,종로동광모닝스카이,15.855,20200107,12250,중소형,4.545455,2695.0
...,...,...,...,...,...,...,...,...
4621,오금동,엘리시움아파트,64.7,20200204,52000,중대형,19.393939,2681.0
4622,오금동,아남,84.93,20200205,86500,중대형,25.454545,3398.0
4623,거여동,거여2단지동아,101.95,20200203,85000,대형,30.606061,2777.0
4624,명일동,삼익그린2차,66.87,20200208,99500,중대형,20.000000,4975.0
4625,길동,길동우성,57.1,20200201,62000,중소형,17.272727,3589.0
4626,길동,청광플러스원큐브3차,13.265,20200201,11000,중소형,3.939394,2792.0
4627,길동,강동큐브,12.49,20200201,11000,중소형,3.636364,3025.0
4628,길동,강동큐브(2차),15.12,20200201,11900,중소형,4.545455,2618.0
4629,길동,삼익세라믹,84.85,20200204,55000,중대형,25.454545,2161.0
4630,길동,동심훼밀리,84.63,20200205,39800,중대형,25.454545,1564.0
4631,길동,청광플러스원큐브3차,13.265,20200207,12500,중소형,3.939394,3173.0
4632,길동,현대웰하임(101동),16.959,20200207,12300,중소형,4.848485,2537.0
4633,길동,경지 Arium,14.33,20200207,21400,중소형,4.242424,5044.0
4634,길동,대상,59.91,20200210,38400,중소형,17.878788,2148.0
4635,길동,라인,59.94,20200210,49900,중소형,17.878788,2791.0
4636,길동,청광플러스원큐브3차,13.265,20200212,12000,중소형,3.939394,3046.0
4637,길동,광남아파트 102동,84.98,20200212,51000,중대형,25.454545,2004.0
4638,둔촌동,프라자,109.07,20200201,94700,대형,33.030303,2867.0
4639,암사동,대은팰리스뷰(102),84.9,20200211,52000,중대형,25.454545,2043.0
4640,성내동,스위트빌(435-10),95.73,20200202,54000,대형,28.787879,1876.0
4641,성내동,동아2,84.71,20200205,53000,중대형,25.454545,2082.0
4642,성내동,포레스(B동),79.73,20200210,60000,중대형,23.939394,2506.0
4643,성내동,인택스파크뷰,142.09,20200210,100000,대형,43.030303,2324.0
4644,천호동,삼익아파트,114.49,20200202,68000,대형,34.545455,1968.0
4645,천호동,현진리버파크,14.9,20200203,18500,중소형,4.242424,4361.0
4646,천호동,래미안강동팰리스,59.98,20200204,95000,중소형,17.878788,5314.0
4647,천호동,강변그대가리버뷰,84.99,20200205,89500,중대형,25.454545,3516.0
4648,천호동,강동이루미아파트,84.88,20200210,53500,중대형,25.454545,2102.0
4649,천호동,집앤사스윗사이드아파트,14.02,20200211,19100,중소형,4.242424,4502.0
4650,천호동,집앤사스윗사이드아파트,14.02,20200211,19000,중소형,4.242424,4479.0

In [104]:
news_df = [i for i in range(26)]
news_df

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [122]:
news_df = [i for i in range(26)]
news_df[0] = pd.Timestamp(datetime.today()).date()
news_df[1] = len(estate[estate["week"] == 1])

In [100]:
for i in range(estate.shape[0]):
    if i < 6:
        estate.iloc[i:i+1,-1] = 1
    else:
        estate.iloc[i:i+1,-1] = 2
estate

              apt     price  area      date size  week
0       경남(2차) 9동  23억6,000   182  20.02.13  초대형     1
1         대청 301동  10억3,000    39  20.02.12  중소형     1
2   주공고층5단지. 503동  19억7,000    74  20.02.11  중대형     1
3   주공고층6단지. 607동       16억    53  20.02.11  중소형     1
4   주공고층6단지. 608동  21억5,000    83  20.02.11  중대형     1
5   주공고층7단지. 706동  19억8,000    73  20.02.10  중대형     1
6   주공고층5단지. 502동       21억    83  20.02.06  중대형     2
7         대치 219동  12억5,000    49  20.02.06  중소형     2
8         대치 209동        9억    33  20.02.06  중소형     2
9     LG개포자이 104동       21억   134  20.02.06  초대형     2
10  주공고층7단지. 706동       20억    73  20.02.03  중대형     2
11  주공고층5단지. 503동  20억1,000    74  20.02.03  중대형     2
12  주공고층6단지. 608동  21억8,000    83  20.02.03  중대형     2
13  래미안블레스티지 201동  17억8,000    59  20.02.03  중소형     2
14  래미안블레스티지 222동  18억5,000    59  20.02.03  중소형     2
15  래미안블레스티지 214동  27억8,000    99  20.02.03  초대형     2
16  주공고층6단지. 603동       16억    53  20.01.31  중소형     2

In [1]:
"서울시 강남구 청담동의 {0} 1주일 이내 아파트 신규 등록 매물 {1}건, 거래량 (매매) {2}건을 기록했다.

평형별 내역의 경우 
중소형(59m2 이하)의 등록 매물은 {3}건으로 지난 주 대비 {4}건 감소했으며 3.3m2당 가격은 {5}만원으로 지난 주 대비 {6}만원 감소했다. 거래 매물은 {7}건으로 지난 주 대비 {8}건 증가했으며 3.3m2당 가격은 {9}만원으로 지난주 대비 {10}만원 증가했다.
중대형(59~84m2)의 등록 매물은 {11}건으로 지난 주 대비 {12}하며 3.3m2당 가격은 {13}만원으로 지난 주 대비 {14}하다. 거래 매물은 {15}건으로 지난 주 대비 {16}건 감소했으며 3.3m2당 가격은 {17}만으로 지난 주 대비 {18}만원 감소했다.
대형(84m2 초과)의 등록 매물은 {19}건으로 지난 주 대비 {20}건 증가했으며 3.3m2당 가격은 {21}만원으로 지난 주 대비 {22}만원 증가했다. 거래 매물은 {23}건으로 지난 주 대비 {24}하며 3.3m2당 가격은 {25}만원으로 지난 주 대비 {26}하다."





# 0: 오늘 날짜
# 1: 신규 등록 매물
# 2: 거래량(매매)    
# 3: 중소형 등록 매물
# 4: 중소형 등록 매물 지난 주 대비    
# 5: 중소형 등록 매물 평당 가격    
# 6: 중소형 등록 매물 평당 가격 지난 주 대비
# 7: 중소형 거래 매물
# 8: 중소형 거래 매물 지난 주 대비    
# 9: 중소형 거래 매물 평당 가격    
# 10: 중소형 거래 매물 평당 가격 지난 주 대비
# 11: 중대형 등록 매물
# 12: 중대형 등록 매물 지난 주 대비    
# 13: 중대형 등록 매물 평당 가격    
# 14: 중대형 등록 매물 평당 가격 지난 주 대비
# 15: 중대형 거래 매물
# 16: 중대형 거래 매물 지난 주 대비    
# 17: 중대형 거래 매물 평당 가격    
# 18: 중대형 거래 매물 평당 가격 지난 주 대비
# 19: 대형 등록 매물
# 20: 대형 등록 매물 지난 주 대비    
# 21: 대형 등록 매물 평당 가격    
# 22: 대형 등록 매물 평당 가격 지난 주 대비
# 23: 대형 거래 매물
# 24: 대형 거래 매물 지난 주 대비    
# 25: 대형 거래 매물 평당 가격    
# 26: 대형 거래 매물 평당 가격 지난 주 대비

SyntaxError: EOL while scanning string literal (<ipython-input-1-36abd4813b37>, line 1)

In [118]:
pd.Timestamp

TypeError: Cannot convert input [0    20200103
Name: date, dtype: object] of type <class 'pandas.core.series.Series'> to Timestamp

,dong,apt,area,date,price,size,pyeong,price_per_3.3,week
0,필운동,신동아블루아광화문의 꿈,111.97,20200103,100000,초대형,33.636364,2973.0,NaN
1,사직동,광화문풍림스페이스본(106동),163.33,20200102,162000,초대형,49.393939,3280.0,NaN
2,내수동,세종로대우,109.91,20200106,88000,초대형,33.030303,2664.0,NaN
3,내수동,킹스매너,194.43,20200109,130000,초대형,58.787879,2211.0,NaN
4,내수동,경희궁 파크팰리스,148.09,20200120,149000,초대형,44.848485,3322.0,NaN
...,...,...,...,...,...,...,...,...,...
4642,천호동,래미안강동팰리스,59.98,20200204,95000,중소형,17.878788,5314.0,NaN
4643,천호동,강변그대가리버뷰,84.99,20200205,89500,중대형,25.454545,3516.0,20200205
4644,천호동,강동이루미아파트,84.88,20200210,53500,중대형,25.454545,2102.0,20200210
4645,천호동,집앤사스윗사이드아파트,14.02,20200211,19000,중소형,4.242424,4479.0,20200211
4646,천호동,집앤사스윗사이드아파트,14.02,20200211,19100,중소형,4.242424,4502.0,20200211