In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
df=pd.read_csv('c:/chosungeun/date.csv')
df.replace(0, np.nan)
df.head(5)

,Name,Date,유동자산계,현금및현금등가물,자본금,자본잉여금,이익잉여금,총자산증가율,자기자본증가율,매출액증가율,...,자산총계,부채총계,자본총계,매출액,매출총이익손실,판매비와관리비,영업이익손실,당기순이익손실,Price,Size
0,(주)BNK금융지주,201102,NaN,5.189200e+07,9.670000e+11,1.640000e+12,-1.746391e+09,3.96,-0.06,NaN,...,2.709760e+12,1.062570e+11,2.603500e+12,2.214270e+08,NaN,1.116814e+09,-1.477453e+09,-1477453000,14950.0,2.0
1,(주)BNK금융지주,201103,NaN,8.984500e+07,9.670000e+11,1.640000e+12,-4.219870e+09,7.41,-0.10,NaN,...,2.910500e+12,3.094700e+11,2.601030e+12,1.652374e+09,NaN,1.077446e+09,-2.473479e+09,-2473479000,13100.0,2.0
2,(주)BNK금융지주,201104,NaN,1.700000e+11,9.670000e+11,1.640000e+12,1.230000e+11,NaN,NaN,NaN,...,3.249910e+12,5.220900e+11,2.727820e+12,1.331760e+11,NaN,1.511417e+09,1.267750e+11,126790000000,11100.0,2.0
3,(주)BNK금융지주,201201,NaN,7.087537e+10,9.670000e+11,1.640000e+12,5.202239e+10,-0.09,-2.59,NaN,...,3.247020e+12,5.897540e+11,2.657270e+12,3.955886e+09,NaN,1.241463e+09,-2.869146e+09,-2864391000,14100.0,2.0
4,(주)BNK금융지주,201202,NaN,2.433287e+09,9.670000e+11,1.640000e+12,4.672493e+10,2.27,-0.20,1549.44,...,3.320850e+12,6.688780e+11,2.651970e+12,3.652297e+09,NaN,2.079435e+09,-5.389360e+09,-5297461000,12050.0,2.0

In [14]:
df['현금및현금등가물'].count()

24855

In [42]:
unique_name=list(df['Name'].unique()) # 중복 제거
len_name=[]
for i in range(len(unique_name)):
    
    len_name.append(sum(df['Name']==unique_name[i]))

len_name

[31,
 36,
 36,
 30,
 36,
 36,
 36,
 10,
 21,
 36,
 36,
 36,
 36,
 36,
 36,
 33,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 29,
 36,
 36,
 36,
 36,
 36,
 36,
 6,
 36,
 36,
 14,
 36,
 36,
 36,
 36,
 35,
 36,
 12,
 36,
 36,
 36,
 36,
 36,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 35,
 36,
 34,
 12,
 36,
 36,
 8,
 34,
 36,
 36,
 36,
 35,
 36,
 36,
 36,
 34,
 36,
 36,
 36,
 10,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 17,
 35,
 31,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 19,
 32,
 36,
 36,
 36,
 36,
 28,
 36,
 30,
 36,
 36,
 36,
 31,
 36,
 17,
 36,
 36,
 32,
 36,
 36,
 35,
 31,
 36,
 36,
 36,
 36,
 12,
 11,
 35,
 36,
 31,
 36,
 36,
 36,
 36,
 30,
 36,
 35,
 36,
 35,
 36,
 36,
 36,
 35,
 36,
 36,
 34,
 35,
 36,
 36,
 36,
 34,
 36,
 36,
 36,
 36,
 36,
 15,
 36,
 36,
 36,
 25,
 36,
 36,
 36,
 36,
 36,
 36,
 6,
 35,
 36,
 36,
 35,
 34,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 31,
 34,
 36,
 35,
 36,
 14,
 30,
 36,
 36,
 36,
 36,
 35,
 36,
 36,
 35,
 36,
 11,
 12,
 35,
 36,
 36,
 18,
 36,
 35,
 20,
 36,
 36,
 36,
 18,
 36,
 28,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 30,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 31,
 33,
 32,
 36,
 36,
 36,
 36,
 36,
 36,
 7,
 35,
 36,
 36,
 36,
 4,
 14,
 36,
 36,
 34,
 36,
 34,
 36,
 36,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 31,
 36,
 36,
 36,
 36,
 36,
 36,
 34,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 20,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 32,
 34,
 36,
 36,
 36,
 36,
 8,
 36,
 36,
 18,
 36,
 35,
 36,
 33,
 36,
 28,
 36,
 14,
 36,
 36,
 36,
 36,
 36,
 35,
 36,
 23,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 31,
 30,
 36,
 36,
 35,
 36,
 35,
 35,
 35,
 36,
 36,
 36,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 34,
 36,
 36,
 36,
 36,
 36,
 36,
 34,
 36,
 36,
 36,
 35,
 7,
 36,
 36,
 36,
 36,
 36,
 36,
 11,
 36,
 36,
 36,
 32,
 32,
 36,
 36,
 36,
 36,
 31,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 32,
 36,
 36,
 36,
 35,
 36,
 36,
 36,
 35,
 35,
 36,
 35,
 23,
 33,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 24,
 36,
 13,
 36,
 36,
 8,
 36,
 36,
 36,
 36,
 35,
 16,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 30,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 35,
 18,
 36,
 7,
 36,
 32,
 36,
 34,
 26,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 26,
 36,
 34,
 36,
 36,
 16,
 8,
 35,
 17,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 34,
 36,
 36,
 36,
 36,
 36,
 10,
 36,
 36,
 36,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 18,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 16,
 36,
 36,
 36,
 36,
 20,
 36,
 36,
 36,
 36,
 3,
 25,
 36,
 35,
 14,
 26,
 36,
 36,
 36,
 13,
 36,
 31,
 35,
 20,
 35,
 36,
 13,
 9,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 7,
 36,
 36,
 36,
 34,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 35,
 36,
 36,
 36,
 36,
 35,
 36,
 36,
 36,
 28,
 9,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 32,
 36,
 36,
 36,
 36,
 9,
 32,
 6,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 25,
 36,
 31,
 36,
 36,
 34,
 31,
 33,
 36,
 36,
 36,
 36,
 12,
 34,
 19,
 35,
 36,
 36,
 36,
 27,
 36,
 31,
 17,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 35,
 34,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 10,
 36,
 36,
 36,
 36,
 36,
 35,
 36,
 36,
 25,
 36,
 24,
 35,
 35,
 33,
 36,
 30,
 34,
 34,
 36,
 33,
 36,
 36,
 30,
 36,
 36,
 16,
 36,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 33,
 36,
 36,
 32,
 36,
 35,
 36,
 36,
 35,
 10,
 11,
 8,
 36,
 6,
 36,
 21,
 36,
 36,
 36,
 35,
 36,
 32,
 6,
 36,
 36,
 36,
 6,
 36,
 12,
 35,
 8,
 36,
 36,
 36,
 36,
 36,
 36,
 35,
 36]

In [32]:
list_columns = df.columns[2:-2]
list_columns

Index(['유동자산계', '현금및현금등가물', '자본금', '자본잉여금', '이익잉여금', '총자산증가율', '자기자본증가율',
       '매출액증가율', '비유동자산계', '영업이익증가율', '순이익증가율', '종업원수증가율', '매출액순이익율', '부채비율',
       '총자본회전율', '자기자본회전율', '투자자산계', '유형자산계', '무형자산계', '유동부채계', '비유동부채계',
       '총자본영업이익율', '총자본순이익율', '자기자본순이익율', '자본금순이익율', '자기자본비율', '자산총계', '부채총계',
       '자본총계', '매출액', '매출총이익손실', '판매비와관리비', '영업이익손실', '당기순이익손실'],
      dtype='object')

In [49]:
len_q=[[61, 60, 62, 61, 61, 60, 60, 62, 61, 59],
 [63, 62, 62, 62, 60, 62, 62, 60, 61, 62],
 [63, 63, 64, 62, 63, 64, 62, 64, 61, 63],
 [65, 63, 62, 62, 62, 63, 63, 57, 62, 62]]
working_day = []
for j in range(10):
    for i in range(len(len_q)):
        working_day.append(len_q[i][j])
working_day = working_day[1:-4]
len(working_day)

35

In [51]:
working_day

[63,
 63,
 65,
 60,
 62,
 63,
 63,
 62,
 62,
 64,
 62,
 61,
 62,
 62,
 62,
 61,
 60,
 63,
 62,
 60,
 62,
 64,
 63,
 60,
 62,
 62,
 63,
 62,
 60,
 64,
 57,
 61,
 61,
 61,
 62]

IndexError: list index out of range